# Partimos de la imagen php en su versión 7.4
FROM php:8.1.0-fpm

# Copiamos los archivos package.json composer.json y composer-lock.json a /var/www/
#COPY ./app/backend/composer*.json /var/www/

# Nos movemos a /var/www/
WORKDIR /var/www/

# Instalamos las dependencias necesarias
RUN apt update && apt install -y build-essential libzip-dev libpng-dev libjpeg62-turbo-dev libfreetype6-dev libonig-dev locales zip jpegoptim optipng pngquant gifsicle vim git curl

# Instalamos extensiones de PHP
RUN docker-php-ext-install pdo_mysql zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Instalamos composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalamos dependendencias de composer
#RUN composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts

# Exponemos el puerto 9000 a la network
EXPOSE 9000
EXPOSE 5173
EXPOSE 6001

# Corremos el comando php-fpm para ejecutar PHP
CMD ["php-fpm"]
